### PR TITLE
Change tests to TDD style, fix assertions performed in suite/describe blocks

### LINKED ISSUE #46: test suite design broken
Test files use `describe` blocks with no `it` blocks. Mocha is configured to use `suite`/`test`, so let's change everything to use those and fix the assertions to not do their own calls to `test`.

### PR DESCRIPTION
**Pull request by benvinegar**
Fixes #46 

Introduces a new utility function, `testParse`, which takes two arguments: 

1. A string representing a program
1. A callback function that accepts a Shift-parsed program. The callback function is invoked as part of a Mocha `test` call.

Example:

```javascript
testParse("(function(){})", function (parsed) {
  expect(expr(parsed)).to.be.eql(
    new Shift.FunctionExpression(null, [], new Shift.FunctionBody([], []))
  )
});
```

Is equivalent to:

```javascript
test("(function(){})", function () {
  expect(ShiftParser.default("(function(){})")).to.be.eql(
  	new Shift.FunctionExpression(null, [], new Shift.FunctionBody([], []))
  )
});
```

The main purpose of `testParse` is to ensure that the Mocha test description is the same as the program string being parsed (for purposes of nice reporting), and also reduce the need to call `ShiftParser.default`.

### CODE REVIEW

File: test/api.js [hunk 1]
```diff
@@ -17,7 +17,7 @@
 var expect = require('expect.js');
 var ShiftParser = require('../');
 
-describe("API", function () {
+suite("API", function () {
   it("should exist", function () {
```
Comment (michaelficarra) [inline test/api.js]: This one should be `test`.

**Comment by michaelficarra** [comment]
This is definitely much better, but I was hoping we could somehow DRY up all the `expect(...).to.be.eql(...)`. How do you feel about making `testParse` take 3 parameters like so:

```js
testParse("(function(){})", expr,
  new Shift.FunctionExpression(null, [], new Shift.FunctionBody([], []))
);
```

**Comment by benvinegar** [comment]
@michaelficarra Yeah sure, let's do that.

**Comment by benvinegar** [comment]
@michaelficarra – so, the problem with that example, is that the third argument:

```javascript
new Shift.FunctionExpression(null, [], new Shift.FunctionBody([], []))
```

Will execute outside/before the `test` call. Which means if there's an exception in that expression, we'll be back to where we were before with an exception thrown outside of the regular test execution / unhelpful test output.

**Comment by michaelficarra** [comment]
Eh, I don't think that's much of a problem. If you write a new, broken test, you know exactly where your error is. The problem before was when the call to `parse` caused an exception.

**Comment by benvinegar** [comment]
> If you write a new, broken test, you know exactly where your error is.

Sure. But to play devil's advocate, what if there's an incompatibility caused by an update to the Shift constructors via shift-ast-js?

If you feel that's not a big deal / acceptable, I'll go ahead with the change.

**Comment by michaelficarra** [comment]
That is certainly a valid concern, but I personally think the trade-off is worth it.

**Comment by michaelficarra** [comment]
I had to fix up a few leftovers, which were easily caught by adding an assertion to the test* functions that they are called with the expected number of arguments. I've left them in to catch potential future errors. Merging.
