### PR TITLE
Test262

### LINKED ISSUE #362: Incorporating Test262
[I recently extended the Test262 project to include additional metadata for "negative" tests](https://github.com/tc39/test262/pull/778). Specifically: tests that are expected to produce early errors and syntax errors can now be automatically distinguished for tests that are expected to produce runtime errors.

My goal was to make the tests consumable by JavaScript parsers. I've since incorporated the tests into [the JSHint project](https://github.com/jshint/jshint), and it's been very useful for fixing bugs and preventing regressions. I'd like to help other Free and Open Source parsers do the same.

Would the maintainers be interested in including Test262 in the automated test suite for this project? If so, I can follow up with some more specific practical questions (e.g. submodule usage, etc.) and go from there.

### PR DESCRIPTION
**Pull request by bakkot**
This adds test262 as a dev dependency, and asserts that every test in it parses or fails to parse as appropriate.

The bulk of this PR is test expectations. These are split into files for ease of maintenance.

Managing expectations is a lot easier since the project adopted feature flags. Part of the test expectations is a list of flags we expect to indicate syntax which isn't parseable; some of these are parseable despite such a flag, and need to be explicitly whitelisted.

The test runner enforces that expectations are not stale: every named test must exist, and every test which is whitelisted as in the above paragraph must refer to an xfailed feature.

No tests are skipped, nor is a mechanism provided to do so.

Fixes #362.

### CODE REVIEW

**Comment by bakkot** [comment]
Note: this should definitely be up-to-date with the es2016 branch before merging.

**Comment by bakkot** [comment]
Also, these are added to the default `npm run test`, which means it takes a lot longer (on my machine, 30 seconds instead of 10). It could be a separate command run by CI, if we want to avoid that.

File: test/test262/expectations/async.js [hunk 1]
```diff
@@ -0,0 +1,165 @@
+'use strict';
+
+// Tests which have neither the `async-functions` nor the `async-iteration` feature flags, but don't use at least one of those features.
```
Comment (michaelficarra) [inline test/test262/expectations/async.js]: *do* use

**Review by michaelficarra — APPROVED** [review]
