### PR TITLE
fix accepting illegal escape sequences

### LINKED ISSUE #279: \u{} is not a legal escape sequence
In strings, directives, or source.

### LINKED ISSUE #280: Octal literals are illegal in directives in strict mode
`"\1"; 'use strict'` is not a program. `"\1"` is.

### PR DESCRIPTION
**Pull request by bakkot**
Fixes #279
Fixes #280

### CODE REVIEW

File: src/parser.js [hunk 1]
```diff
@@ -239,12 +242,18 @@ export class Parser extends Tokenizer {
...
+          if (directiveOctal && this.strict) {
+            throw directiveOctal;
+          }
           statements.push(stmt);
         }
       } else {
         statements.push(stmt);
       }
     }
+    if (directiveOctal && this.strict) {
```
Comment (bakkot) [inline src/parser.js:254]: This condition is only hit if there are no non-directive statements (in which L245 is not reached).

Strictly speaking L245 is redundant, but I think it's best to throw the error after parsing just the directives instead of waiting until we've parsed the entire body.

File: src/tokenizer.js [hunk 2]
```diff
@@ -669,6 +669,10 @@ export default class Tokenizer {
       if (ch !== "}") {
         throw this.createILLEGAL();
       }
+      if (i === this.index + 1) {
+        ++this.index;
```
Comment (bakkot) [inline src/tokenizer.js]: This is so that the error is 'Unexpected "}"' instead of 'Unexpected "{"'.

**Comment by michaelficarra** [comment]
LGTM.
